services:
  - type: static
    name: bhatkar-fragrance-hub-5
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://bhatkar-fragrance-hub-1.onrender.com/api
